server:
  port: 22663

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/subscription?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: subscription
    password: subscription1)G]gSC[Xre
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 600000
      max-lifetime: 1800000
      auto-commit: true
      connection-init-sql: SET NAMES utf8mb4
      leak-detection-threshold: 0
      validation-timeout: 5000
      register-mbeans: true
      allow-pool-suspension: false
